### ISSUE TITLE
NoSuchMethodError with Play 2.6.5

### ISSUE THREAD

**Issue by mvdstam** [irundaia/sbt-sassify#28]
Hi,

Since Play 2.6.5, `sbt-sassify` doesn't seem to work properly, causing a internal server error:

```sh
[info] Sass compiling on 1 source(s)
java.lang.NoSuchMethodError: com.typesafe.sbt.web.CompileProblems$.report(Lsbt/LoggerReporter;Lscala/collection/Seq;)V
        at org.irundaia.sbt.sass.SbtSassify$$anonfun$7$$anonfun$9.apply(SbtSassify.scala:116)
        at org.irundaia.sbt.sass.SbtSassify$$anonfun$7$$anonfun$9.apply(SbtSassify.scala:85)
        at com.typesafe.sbt.web.incremental.package$.syncIncremental(package.scala:228)
        at org.irundaia.sbt.sass.SbtSassify$$anonfun$7.apply(SbtSassify.scala:133)
        at org.irundaia.sbt.sass.SbtSassify$$anonfun$7.apply(SbtSassify.scala:67)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[error] (web-assets:sassify) java.lang.NoSuchMethodError: com.typesafe.sbt.web.CompileProblems$.report(Lsbt/LoggerReporter;Lscala/collection/Seq;)V
```

I'm using `sbt-sassify` version `1.4.9`.

Please let me know if you need any more information. Thanks!

**Comment by amedeomantica** [comment]
it is broken in 2.6.3 too

**Comment by luisnuxx** [comment]
Same here, for 2.6.5

```
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[trace] Stack trace suppressed: run last web-assets:sassify for the full output.
[error] (web-assets:sassify) java.lang.NoSuchMethodError: com.typesafe.sbt.web.CompileProblems$.report(Lsbt/LoggerReporter;Lscala/collection/Seq;)V
[ERROR] [09/16/2017 18:26:38.111] [play-dev-mode-akka.actor.default-dispatcher-7] [akka.actor.ActorSystemImpl(play-dev-mode)] Internal server error, sending 500 response
scala.MatchError: java.lang.NoSuchMethodError: com.typesafe.sbt.web.CompileProblems$.report(Lsbt/LoggerReporter;Lscala/collection/Seq;)V (of class java.lang.NoSuchMethodError)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at scala.util.Either$LeftProjection.map(Either.scala:377)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:17)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$3.apply(PlayRun.scala:71)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$3.apply(PlayRun.scala:71)
	at play.runsupport.Reloader$$anonfun$reload$1.apply(Reloader.scala:413)
	at play.runsupport.Reloader$$anon$5.run(Reloader.scala:51)
	at java.security.AccessController.doPrivileged(Native Method)
	at play.runsupport.Reloader$.play$runsupport$Reloader$$withReloaderContextClassLoader(Reloader.scala:47)
	at play.runsupport.Reloader.reload(Reloader.scala:411)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:123)
	at play.core.server.AkkaHttpServer.modelConversion(AkkaHttpServer.scala:183)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:189)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$3(AkkaHttpServer.scala:106)
	at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by irundaia** [comment]
Thanks for the report, I'll only be able to have a look at it tomorrow evening unfortunately.

**Comment by mvdstam** [comment]
Cheers @irundaia! Can you please release and publish when you fix this?

Thanks!

**Comment by irundaia** [comment]
@mvdstam that's the idea :)

**Comment by adridadou** [comment]
It looks like the error in the pull request that was merged some time ago (but in no release)
Maybe all you need to do is making a release 

https://github.com/irundaia/sbt-sassify/pull/26

**Comment by mvdstam** [comment]
Ping @irundaia

**Comment by irundaia** [comment]
I can confirm that the PR that was merged a couple weeks ago fixes this issue. Unfortunately, I wasn't aware that this would prevent issues with play 2.6.5. I'll see what it takes to release the fix for both sbt 0.13 and 1.0.0

**Comment by rwalus** [comment]
@irundaia  I don't know if I understood you well ... but I need the patch so please drop the tutorial as you get rid of the sassify error..

thx!

**Comment by TonnyGaric** [comment]
I can also confirm that `sbt-sassify` doesn't seem to work properly in `Play 2.6.5`, causing a internal server error. I am also waiting on the fix to be released.

**Comment by irundaia** [comment]
@TonnyGaric @rwalus @mvdstam @adridadou @luisnuxx @amedeomantica, I’ve released version 1.4.10 yesterday. Could you check whether this version solves your issues?

**Comment by mvdstam** [comment]
@irundaia Cheers, I'll let you know asap if `1.4.10` runs with Play `2.6.5`.

**Comment by adridadou** [comment]
@irundaia did you compile it with Java 9 ? because I get this error messge:
java.lang.UnsupportedClassVersionError: org/irundaia/sass/jna/SassLibrary has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by irundaia** [comment]
@adridadou, d'oh! I've set the target jre version to 1.8. I've uploaded v1.4.11. Could you have a try with that version?
It works in my VM. But I just want to make sure that it works for you.

**Comment by adridadou** [comment]
it works much better! Thank you !

**Comment by rwalus** [comment]
Java 9? ..... 


I do not have java 8, but I keep getting the error :(
@irundaia You can do it? ... please...

```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

```
java.lang.UnsupportedClassVersionError: org/irundaia/sass/jna/SassLibrary
	at org.irundaia.sass.Context$.apply(Context.scala:33)
	at org.irundaia.sass.SassCompiler$.doCompile(SassCompiler.scala:57)
	at org.irundaia.sass.SassCompiler$.compile(SassCompiler.scala:40)
	at org.irundaia.sbt.sass.SbtSassify$$anonfun$7$$anonfun$9$$anonfun$10.apply(SbtSassify.scala:93)
	at org.irundaia.sbt.sass.SbtSassify$$anonfun$7$$anonfun$9$$anonfun$10.apply(SbtSassify.scala:93)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.irundaia.sbt.sass.SbtSassify$$anonfun$7$$anonfun$9.apply(SbtSassify.scala:93)
	at org.irundaia.sbt.sass.SbtSassify$$anonfun$7$$anonfun$9.apply(SbtSassify.scala:85)
	at com.typesafe.sbt.web.incremental.package$.syncIncremental(package.scala:228)
	at org.irundaia.sbt.sass.SbtSassify$$anonfun$7.apply(SbtSassify.scala:133)
	at org.irundaia.sbt.sass.SbtSassify$$anonfun$7.apply(SbtSassify.scala:65)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (client/web-assets:sassify) java.lang.UnsupportedClassVersionError: org/irundaia/sass/jna/SassLibrary
```

**Comment by irundaia** [comment]
@rwalus, could you let me know which version of sbt-sassify, sbt, scala and java you’re using?

**Comment by mvdstam** [comment]
Hi @irundaia, I can confirm that version `1.4.11` works with Play `2.6.5`. For sake of completeness, I'm running Scala 2.12 and Java 1.8.

Thanks for the quick fix, and thanks for the awesome plugin! 😃

**Comment by steffenhaak** [comment]
@irundaia: Thanks for the quick fix! You saved my day :)

**Comment by amedeomantica** [comment]
Cool !

**Comment by motilio** [comment]
Hi @irundaia, It seems that version 1.4.11 is working with Play 2.6.6, Scala 2.12.3, Java 1.8. 

Thanks!

**Comment by Spenhouet** [comment]
I had to find this thread to see that version `1.4.11` is available. Could it be that it is not tagged on GitHub?

**Comment by irundaia** [comment]
@Spenhouet it is entirely possible, I'll check in an hour or so whether I can fix that. Apologies for the inconvenience

**Comment by abdelrahmanmohamed** [comment]
@irundaia I have the same issue with play 2.6.11 and scala version 11
