### ISSUE TITLE
Play/Scala, JDK17, Apple M1: NoClassDefFoundError: Could not initialize class com.sun.jna.Native

### ISSUE THREAD

**Issue by michbarsinai** [irundaia/sbt-sassify#51]
When working with Play, using JDK17 on Apple Silicon M1, I get the below stack trace. The problem is solved when moving back to JDK11.

(sbt 1.6.2, Play 2.8.15)

````
[info] Sass compiling on 7 source(s)
[error] stack trace is suppressed; run last Web-assets / sassify for the full output
[error] (Web-assets / sassify) java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:524)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
````

**Comment by irundaia** [comment]
Hi Michael,

Could you clarify which version of sbt-sassify you're using? I'm trying to reproduce this issue, but I cannot on my intel Mac.

**Comment by michbarsinai** [comment]
I have this on my plugins.sbt:

addSbtPlugin("io.github.irundaia" % "sbt-sassify" % "1.5.2")

I'm happy to try test versions on my M1 Mac as needed.

-- Michael

**Comment by irundaia** [comment]
Great that you'd like to help resolve this issue. Would it be possible for you to provide your plugins.sbt and build.sbt files? I personally wouldn't expect this to be an CPU architecture issue, but rather a dependency conflict.

**Comment by michbarsinai** [comment]
plugins.sbt

```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.15")

addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.6")

addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.4")

addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.1.2")

addSbtPlugin("com.typesafe.sbt" % "sbt-gzip" % "1.0.2")

addSbtPlugin("io.github.irundaia" % "sbt-sassify" % "1.5.2")
```

build.sbt:

```
import play.sbt.PlayImport.caffeine

name := """XXXXX"""

organization := "XXXX"

maintainer := "XXXXXXX"

version := "0.7-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.13.7"

// Targeting JDK11, which is the current LTS
javacOptions ++= Seq("-source", "11", "-target", "11")

libraryDependencies ++= Seq(
  caffeine,
  ws,
  guice,
  "com.google.inject"            % "guice"                % "5.1.0", /* Needed for JDK17 */
  "com.google.inject.extensions" % "guice-assistedinject" % "5.1.0", /* Needed for JDK17 */
  "io.methvin" % "directory-watcher" % "0.15.0", /* Required for M1 */
  "com.typesafe.play" %% "play-slick" % "5.0.0",
  "com.typesafe.play" %% "play-slick-evolutions" % "5.0.0",
  "com.typesafe.play" %% "play-mailer" % "8.0.0",
  "com.typesafe.play" %% "play-mailer-guice" % "8.0.0",
  "be.objectify" %% "deadbolt-scala" % "2.7.1",
  "org.mindrot" % "jbcrypt" % "0.3m",
  "org.postgresql" % "postgresql" % "42.2.11",
  "org.webjars" % "jquery" % "3.6.0",
  "org.webjars" % "jquery-ui" % "1.12.1",
  "org.webjars.bower" % "tether" % "1.4.7",
  "org.webjars" % "popper.js" % "2.9.2",
  "org.webjars" % "sweetalert" % "2.1.0",
  "org.webjars.bower" % "polyglot" % "2.2.2",
  "org.webjars" % "bootstrap" % "5.1.3",
  "org.webjars.bower" % "fontawesome" % "4.7.0",
  "org.scalatestplus.play" %% "scalatestplus-play" % "4.0.3" % Test,
  "org.seleniumhq.selenium" % "selenium-java" % "2.35.0" % Test,
)


import org.irundaia.sbt.sass._

SassKeys.cssStyle := Minified

SassKeys.generateSourceMaps := true

// Needed for M1/Apple Silicon
PlayKeys.fileWatchService := play.dev.filewatch.FileWatchService.jdk7(play.sbt.run.toLoggerProxy(sLog.value))

TwirlKeys.templateImports ++= Seq("views.Helpers")

pipelineStages := Seq(digest, gzip)

// Disable documentation creation
Compile / doc / sources  := Seq.empty
Compile / packageDoc / publishArtifact := false
```

**Comment by giannoug** [comment]
Same issue here on an Apple M1 machine. Using sbt 1.4.9 and Play 2.7.9.

```
[error] stack trace is suppressed; run last my-project / Web-assets / sassify for the full output
[error] (my-project / Web-assets / sassify) java.lang.UnsatisfiedLinkError: /Users/user/Library/Caches/JNA/temp/jna4151150526563459761.tmp: dlopen(/Users/user/Library/Caches/JNA/temp/jna4151150526563459761.tmp, 0x0001): tried: '/Users/user/Library/Caches/JNA/temp/jna4151150526563459761.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/user/Library/Caches/JNA/temp/jna4151150526563459761.tmp' (no such file), '/Users/user/Library/Caches/JNA/temp/jna4151150526563459761.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))
[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:506)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:376)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:485)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764
```

**Comment by cheburan** [comment]
Any luck with this?

**Comment by ruddhikamm** [comment]
[info] Sass compiling on 6 source(s)
[trace] Stack trace suppressed: run last web-assets:sassify for the full output.
[error] (web-assets:sassify) java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/hv/dytqzpts2fd675j4rsbp6p2c0000gp/T/jna-1086956152/jna6666156284613827565.tmp
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
scala.MatchError: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/hv/dytqzpts2fd675j4rsbp6p2c0000gp/T/jna-1086956152/jna6666156284613827565.tmp (of class java.lang.UnsatisfiedLinkError)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at scala.util.Either$LeftProjection.map(Either.scala:377)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:17)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
	
Facing Same Issue. JDK 8 Apple silicon M1

**Comment by Montesk** [comment]
Hello! Facing the same issue on my Mac Ventura 13, M2 Pro

When running `sbt test` or `sbt run` over my play framework app (2.9.4 - current latest for scala 2)

Scala version: 2.13.14
Java: zulu 21
Sbt: 1.10.0
Sassify:
`addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.5.1" withSources ())`

Relevant stack trace:

```
[error] (Web-assets / sassify) java.lang.UnsatisfiedLinkError: dlopen(/Users/hq-rv7cm7t7yy/Library/Caches/JNA/temp/jna8830028985985827204.tmp, 0x0009): tried: '/Users/hq-rv7cm7t7yy/Library/Caches/JNA/temp/jna8830028985985827204.tmp' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/hq-rv7cm7t7yy/Library/Caches/JNA/temp/jna8830028985985827204.tmp' (no such file), '/Users/hq-rv7cm7t7yy/Library/Caches/JNA/temp/jna8830028985985827204.tmp' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

I've also tried
- run sbt run/test under java 11, 14, 17, 21, 24
- update libsass 
- install macports on my system and rebooted the system 
- delete and compiled files in the project and recompile it from scratch
- run sbt clear cache, updateClassifiers, updateSbtClassifiers

Everything works fine on ubuntu 20, windows (Intel)

Full stack trace:

```
[info] Sass compiling on 6 source(s)
[error] java.lang.UnsatisfiedLinkError: dlopen(/Users/hq-rv7cm7t7yy/Library/Caches/JNA/temp/jna4888529949339655161.tmp, 0x0009): tried: '/Users/hq-rv7cm7t7yy/Library/Caches/JNA/temp/jna4888529949339655161.tmp' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/hq-rv7cm7t7yy/Library/Caches/JNA/temp/jna4888529949339655161.tmp' (no such file), '/Users/hq-rv7cm7t7yy/Library/Caches/JNA/temp/jna4888529949339655161.tmp' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
[error]         at com.sun.jna.Native.open(Native Method)
[error]         at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:298)
[error]         at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483)
[error]         at com.sun.jna.Library$Handler.<init>(Library.java:197)
[error]         at com.sun.jna.Native.loadLibrary(Native.java:672)
[error]         at com.sun.jna.Native.loadLibrary(Native.java:656)
[error]         at org.irundaia.sass.SassCompiler$.<init>(SassCompiler.scala:28)
[error]         at org.irundaia.sass.SassCompiler$.<clinit>(SassCompiler.scala)
[error]         at org.irundaia.sbt.sass.SbtSassify$.$anonfun$baseSbtSassifySettings$10(SbtSassify.scala:100)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at org.irundaia.sbt.sass.SbtSassify$.$anonfun$baseSbtSassifySettings$8(SbtSassify.scala:100)
[error]         at com.typesafe.sbt.web.incremental.package$.syncIncremental(package.scala:109)
[error]         at org.irundaia.sbt.sass.SbtSassify$.$anonfun$baseSbtSassifySettings$6(SbtSassify.scala:140)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error]         at sbt.Execute.work(Execute.scala:292)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error]         at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by michbarsinai** [comment]
@Montesk Note that version 1.5.2 is out, which might help. 

I eventually migrated all my projects to Play 3 and Scala 3, which solved all these issues. I was able to transfer most projects in less than a day (per project). Obviously it's not always that easy, but if possible it might save you a lot of future headache.

**Comment by Montesk** [comment]
@michbarsinai Hello! Thanks a lot for your reply I finally was able to recognize the plugin path changed to "io." as prefix after that and it really **helped**! `io.github.irundaia` instead of `org.github.sbt`. Tests passed and project compiled

I have no doubts scala 3 is better choice to migrate and im planning to do it shortly. Actually I've tried it when was trying to solve the issue, it seems like i have near 20-30 compilation errors and finally will handle the migration.

Thanks again!
